CODE_GEN_TYPE_HTML = "html"
CODE_GEN_TYPE_MULTI_FILE = "multi_file"
CODE_GEN_TYPE_VUE_PROJECT = "vue_project"

SUPPORTED_CODE_GEN_TYPES = {
    CODE_GEN_TYPE_HTML,
    CODE_GEN_TYPE_MULTI_FILE,
    CODE_GEN_TYPE_VUE_PROJECT,
}
